// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WindowsFormsApp2.Models
{
    [Table("application")]
    public partial class Application
    {
        [Key]
        [Comment("Primary key")] // allows for documenting besides a summary section
        [Column("ID")]
        public int Id { get; set; }
        [StringLength(45)]
        [Column("short_name")]
        public string ShortName { get; set; }
        [StringLength(255)]
        [Column("long_name")]  
        public string LongName { get; set; }
        [StringLength(1)]
        [Column("active_flag")]
        public string AactiveFlag { get; set; }
        [Column("start_outage")]
        public DateTime? StartOutage { get; set; }
        [Column("end_outage")]
        public DateTime? EndOutage { get; set; }
        [Column("start_notice")]
        public DateTime? StartNotice { get; set; }
        [StringLength(2500)]
        [Column("notice_text")]
        public string NoticeText { get; set; }
        [StringLength(2500)]
        public string outage_text { get; set; }
        [Column("lmod_date")]
        public DateTime? ModifiedDateTime { get; set; }
        [StringLength(100)]
        [Column("dest_url")]
        public string DestinationAddress { get; set; }
        [StringLength(2500)]
        [Column("comment_text")]
        public string Comment { get; set; }
        [StringLength(255)]
        [Column("prod_url")]
        public string ProductionAddress { get; set; }

        public override string ToString() => $"{Id}";

    }
}